function initializeGraphs(handles)

global rstr 

colormap('gray')

% Preassign rasters 
nStim      = get(handles.nStim,'UserData');
edges      = -0.1 : 0.001 : 0.4;
nEdges     = length(edges);
Zdata      = rand(nStim, nEdges);

rstr.edges = edges;
rstr.nStim = nStim;

xtick = [1 find(edges == 0) nEdges];
xlabl = {'-0.1','0','0.4'};

% % Set rasters to channels 1, 2 and 3
% set(handles.leftRasterChan, 'value', 1)
% set(handles.centerRasterChan, 'value', 2)
% set(handles.rightRasterChan, 'value', 3)

% Store memory of selected channels
rstr.chans = [1 2 3];

% Clear any existing graphs
cla([handles.leftRaster handles.centerRaster handles.rightRaster])
        
% Draw rasters
axes(handles.leftRaster)
hold on
rstr.im(1) = imagesc(Zdata);
set(gca,...
            'xtick',xtick,...
            'xticklabel',xlabl,...
            'xlim',[0 nEdges],...
            'ylim',[0.5 nStim+0.5],...
            'FontSize',7,...
            'XLimMode','manual',...
            'YLimMode','manual',...
            'ZLimMode','manual',...
            'CLimMode','manual',...
            'ALimMode','manual',...
            'ydir','reverse')
        xlabel('Time (s)')
        ylabel('Trial')

        
        

        

axes(handles.centerRaster)
hold on
rstr.im(2) = imagesc(Zdata);

set(gca,...
            'xtick',xtick,...
            'xticklabel',xlabl,...
            'xlim',[0 nEdges],...
            'ylim',[0.5 nStim+.5],...
            'FontSize',7,...
            'XLimMode','manual',...
            'YLimMode','manual',...
            'ZLimMode','manual',...
            'CLimMode','manual',...
            'ALimMode','manual',...
            'ydir','reverse')
        xlabel('Time (s)')
        ylabel('Trial')
        
        
axes(handles.rightRaster)
hold on
rstr.im(3) = imagesc(Zdata);
set(gca,...
            'xtick',xtick,...
            'xticklabel',xlabl,...
            'xlim',[0 nEdges],...
            'ylim',[0.5 nStim+0.5],...
            'FontSize',7,...
            'XLimMode','manual',...
            'YLimMode','manual',...
            'ZLimMode','manual',...
            'CLimMode','manual',...
            'ALimMode','manual',...
            'ydir','reverse')
        xlabel('Time (s)')
        ylabel('Trial')
        
        
        
% Initialize arguments on first run        
rstr.sev = zeros(48,1);

rstr.tev = cell(48,1);

for i = 1 : 48,
    rstr.tev{i} = 0;
end        

rstr.stimIdx = 0;
rstr.stimTimes = [];
